name: scrollable_reorderable_navbar
description: A bottom nav bar that can be scrolled when there are than 5 nav items to display. It also let user swipe items position and item can be deleted from the navbar.
version: 0.0.1
homepage: https://github.com/AlexisDeslandes/scrollable_reorderable_navbar

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  mocktail: ^0.2.0


flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: